language: node_js
node_js:
  - "8"
env:
  global:
    - PORT=8080
    - DB_HOST=127.0.0.1
    - DB_PORT=3306
    - DB_USER=travis
    - DB_PASSWORD=secret

services:
  - mysql

before_install:
  - mysql -u root -e "SET PASSWORD FOR 'travis'@'localhost' = PASSWORD('secret')"
  - mysql -u travis --password="secret" < db-scripts/create_database.sql

script: npm run test:all
