version: '2.1'
services:
  app:
    build: .
    environment:
      - PORT=8080
      - MYSQL_URL=mysql
    ports:
      - "8080:8080"
      - "5858:5858"
    links:
      - mysql
    volumes:
      - .:/app/
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
